### ISSUE TITLE
find_no_element_ok will close the browser session

### ISSUE THREAD

**Issue by hoodie63** [gempesaw/Selenium-Remote-Driver#155]
Calling find_element with a non-existent element causes the Selenium Server to crash and close the session.

So what should be a success for this method will end the browser session.  The try/catch just keeps the test program from croaking.

The find_element_ok method will also close the session if called with a non-existent element except that it will also crash the test program.

Since everyone seems to advocate calling find_elements to check if an element exists, it would be very nice if each of these methods used find_elements and only call find_element if the element does exist.

**Comment by gempesaw** [comment]
I must be missing something - what am I doing wrong to reproduce the problem?

```perl
#! /usr/bin/perl

use strict;
use warnings;
use feature qw/say/;
use Test::Selenium::Remote::Driver;
use Test::Exception tests => 2;

my $t = Test::Selenium::Remote::Driver->new;
$t->get('http://www.google.com');

lives_ok( sub { $t->find_no_element_ok('missing', 'no element found') }, 'find_no_element_ok passes without crashing' );

say $t->get_title;
```

returns

```
1..2
ok 1 - no element found
ok 2 - find_no_element_ok passes without crashing
Google
```

Nothing crashed?

**Comment by peroumal1** [comment]
Hmmm, this is weird. 
IIRC, `find_element` when called used to crash the Selenium Server session (see @remorse comments on issue #96). So the fact that you are still able to call `get_title` looks weird to me, or am I missing something ? 
As for `find_no_element_ok`, I checked the implementation and there is a `try  { ... } catch { ... }` around the `find_element` call, so it should not crash at all.

**Comment by hoodie63** [comment]
Did your selenium driver connection to the PC stay up? That's what crashes,
not the test itself.

**Comment by gempesaw** [comment]
Yes, everything stayed up. The server thinks the session is still open, and I was still able to send it commands. Slightly more complicated this time around, but:

```perl
#! /usr/bin/perl

use strict;
use warnings;
use feature qw/say/;
use Test::Selenium::Remote::Driver;
use Test::Exception tests => 3;

my $t = Test::Selenium::Remote::Driver->new( default_finder => 'name' );
say 'My session id is: ' . $t->{session_id};
$t->get('http://www.google.com');

lives_ok( sub { $t->find_no_element_ok('missing', 'no element found') }, 'find_no_element_ok passes without crashing' );

$t->find_element_ok('q', 'we can find an existing element afterwards');

say 'The page title is: ' . $t->get_title;
say 'The webdriver server still has the following sessions: ';
map { say $_->{id} } @{ $t->get_sessions };

$t->quit;
```
It opens a session, fail to find an element with `find_no_element_ok`, making sure it doesn't crash on the client side with `lives_ok`. Afterwards, we send some more commands to the webdriver session: we check the title and successfully find the search box at `name=q`. Finally, we print out the list of all existing sessions before quitting manually. 

```
1..3
My session id is: a8de931e-5f92-4205-ba78-873301252e6e
ok 1 - no element found
ok 2 - find_no_element_ok passes without crashing
ok 3 - we can find an existing element afterwards
The page title is: Google
The webdriver server still has the following sessions: 
a8de931e-5f92-4205-ba78-873301252e6e
```

Perhaps there's a version mismatch somewhere? I'm 2.44.0 of webdriver and 0.2203 of S::R::D.

**Comment by peroumal1** [comment]
On the snippet provided by @gempesaw, the connection stays up, since he calls `get_title` afterwards : he won't have been able to do that if the connection was broken. 
From the tests I conducted, the connection will be closed only if the `find_element` failing is not caught (not between a `try { ... } catch { ... };` block or `eval`).
@gempesaw, as a side note, we might have an issue with our implementation of `find_element`. The thing is, we could prevent `find_element` from croaking (and the session to be destroyed) if we don't die on errors from the Selenium Server.

**Comment by gempesaw** [comment]
Yes, we don't necessarily have to croak in that case. But I'm not sure what other behavior is reasonable. We can't instantiate a WebElement because we don't have a valid element_id, but whatever we pass back, the user will try to invoke ::WebElement methods on, because the script hasn't died, such as

    $d->find_element('missing')->send_keys('whee');

At which point the result of `find_element` must either have the same interface as WebElement (or maybe the `Null AUTOLOAD { $self } object`)? Now, we'd be reporting on errors in our code (like `$fake_not_webelement_thing doesn't have a method send_keys`), instead of on the actual issue that the server couldn't find anything. :( (Or, if we went the `Null` way, the user would eventually have to check that they got a S::R::WebElement vs a Null, which feels just as messy as wrapping a try catch or `find_elements` first.)

**Comment by peroumal1** [comment]
Yeah that looks painful, I get it :) 
I see in issue #96 that you explain that the behaviour we have is quite a common one in other Selenium language bindings, so I guess this is the best we can do :(

**Comment by gempesaw** [comment]
yeah. definitely unsatisfactory behavior, though :(

**Comment by remorse** [comment]
I'm not sure if this is a useful idea or not, but I think the question of what to do really depends on what domain it is being used in. For testing, it makes sense that things should crash when something is not found. But for automation, I can easily see times where it makes sense to forge ahead. For instance, you may want to check a checkbox if it exists, but otherwise not worry about it.

Perhaps you could have a chaining version of find_element, similar to the null object idea above, with the extension that it boolifies to (or maybe undef?). Then, if I care whether or not the find worked, I can wrap it in an `if`. Something like:

```perl
# faff around and get a connection as $d

# I don't care if this actually can be done:
$d->find_element_chain('add-extra-magical-behaviour')->click();

# I want to take some actions if this does work
if ($d->find_element_chain('open-settings-panel')->click()) {
    $d->find_element('settings-dont-crash')->click();
    $d->find_element('settings-name')->send_keys('master of the universe');
}
```

In the first example, if the `add-extra-magical-behaviour` checkbox can be found, then click it, but otherwise just get on with the task (maybe it doubles the speed of the server, or something like that). In the second example, I can't change settings if the `open-settings-panel` checkbox doesn't exist (maybe because I don't have sufficient administrator privileges), but there may be other tasks I can do even if I can't modify the settings.

Maybe this doesn't make sense; I'm not sure.

**Comment by gempesaw** [comment]
No, that definitely makes sense. Internally we have this exact distinction in our test DSL between `verify` and `assert` - verify is bad but not test-endingly-bad, whereas asserts must die if they're not passed. Currently, one way to do your example would be

```perl
use Try::Tiny;
try { $d->find_element('magic-tricks')->click; };

try {
    $d->find_element('open-settings')->click;
    $d->find_element('stuff')->click;
    $d->find_element('other-stuff')->send_keys('wonder woman');
};
```

just because I personally like `Try::Tiny` more than `eval`. But those `try`s could just as well be `eval`s.

Perhaps the helper functions that have been proposed around like `$driver->click('locator')` and `$driver->send_keys('locator', 'stuff to type');` that shortcut the find_element in favor of a less verbose command should do the not-croaking kind of stuff ? Since they're not yet implemented, it won't break anyone's existing functionality, and it would make available the not-croaking version of things along with the shortcut version of all of them. ??

**Comment by gempesaw** [comment]
Summary of strategies for handling element finding & exceptions: https://github.com/gempesaw/Selenium-Remote-Driver/issues/96#issuecomment-94179616

Feel free to re-open if you have a specific issue! Thanks so much.
