### ISSUE TITLE
Selenium Web Driver Execution stop when running along with Fiddler

### ISSUE THREAD

**Issue by SeanArkin** [gempesaw/Selenium-Remote-Driver#197]
Hello,

Good afternoon. I am running a selenium webdriver scripts using perl but the execution will stop the moment fiddler is launched. If this is related in setting up proxy please post a sample config/code. Thank you.

**Comment by gempesaw** [comment]
What are you trying to do with Fiddler? If you're trying to capture request/response information, you may be interested in [Browsermob::Proxy](https://metacpan.org/pod/Browsermob::Proxy). 

If you want to use Fiddler, you need to use the `proxy` desired capability when instantiating your browser. The method for this is different per browser - Firefox requires you to make a new profile, but Chrome and IE should let you specify it using the proxy cap during construction. Browsermob::Proxy helps take care of that stuff for you, though.

**Comment by gempesaw** [comment]
hmm let us know if you're still having trouble. it'd be easier to help if you can post the code that you're using to start up S:R:D. here's how I do mine for chrome. this assumes you have an proxy on 127.0.0.1:8081:

my $d = Selenium::Remote::Driver->new(
    browser_name => 'chrome',
    proxy => {
        proxyType => 'manual',
        httpProxy => 'http://127.0.0.1:8081',
        sslProxy => 'http://127.0.0.1:8081'
    }
);

for firefox it's slightly more complicated, since you have to make a profile. here's a bit of a summary in the browsermob proxy docs: https://metacpan.org/pod/Browsermob::Proxy#firefox_proxy

as mentioned, let us know if you're still having issues. just going through and cleaning up the issues here :)
