### ISSUE TITLE
$driver->alert_text_like(regexp) probably does not work correctly.

### ISSUE THREAD

**Issue by tomas-zemres** [gempesaw/Selenium-Remote-Driver#213]
```
my $driver = Test::Selenium::Remote::Driver->new(...);
...

# Why test 1 does not failed?
$driver->alert_text_like(qr/xxx/);

# Why test 2 does not failed?
$selenium->alert_text_is('xxx');

# This test 3 files as expected:
is($selenium->get_alert_text(), 'xxx');
```

Test 3 results:
```
        #   Failed test at test_file.pl line 75.
        #          got: 'Are you sure you want to delete this user?'
        #     expected: 'xxx'
```

why test 1 & 2 do not fail? They are probably not executed.

**Comment by peroumal1** [comment]
Hello. 

We are going to need a bit more than that to help you with your issue. 

First, can you provide a HTML snippet of that raises the error ? It is really hard for us to figure out what is wrong just with the code provided. 

Second, with the HTML snippet provided, can you provide also a correct code snippet that raises the error you are experiencing ? 

Last, can you give us more information on the environment you use : Perl version, S::R::D version, browser on which the issue is reproduced, or any other information that seems relevant. 

Thank you.

**Comment by freddyvega** [comment]
and can you also show the output for tests 1 and 2?

**Comment by tomas-zemres** [comment]
I'm analysing the case where it is working incorrectly.

**Comment by tomas-zemres** [comment]
I'am not able simply reproduce the problem, but I identify the problem:

Problem is in package "Test::Selenium::Remote::Role::DoesTesting", because there is stored instance of Test::Builder. If I use shared instance of selenium-driver than the driver reports test results to wrong Test::Driver instance.

( It contains similar bug that I fixed here: https://github.com/rgs/Test-LongString/pull/5 ) 

There should be called Test::Builder->new() for each test. see implementation of functions "is", "like", etc. in module Test::More.

When I modify "Test::Selenium::Remote::Role::DoesTesting" with following patch:
```
13,17c13,22
< has _builder => (
<     is      => 'lazy',
<     builder => sub { return Test::Builder->new() },
<     handles => [qw/is_eq isnt_eq like unlike ok croak/],
< );
---
> sub builder {
>     return Test::Builder->new();
> }
>
> sub is_eq { shift->builder->is_eq(@_) }
> sub isnt_eq { shift->builder->isnt_eq(@_) }
> sub like { shift->builder->like(@_) }
> sub unlike { shift->builder->unlike(@_) }
> sub ok { shift->builder->ok(@_) }
> sub croak { shift->builder->croak(@_) }
142a148
```
then all tests work ok.

**Comment by peroumal1** [comment]
I'm not 100% confident on your fix, because according to [Test::Builder](https://metacpan.org/pod/Test::Builder#Construction) documentation, the Test::Builder object is a singleton, which means that calling `new()` won't create a new object but always return the same object that was instanciated when calling `new()` the first time. 

Plus, what do you mean by "using a shared selenium instance" ? Can you give me an example of that ? This might help us understand the whole context of the issue. 

Thanks.

**Comment by tomas-zemres** [comment]
I'm using Test::BDD::Cucumber that internally calls Test::Builder->create.
If Selenium::Remote::Driver calls Test::Builder->new before that,
than some test-results are ignored (I think).

("using a shared selenium instance" means: I am using one Test::Selenium::Remote::Driver instance for many test-cases, to minimalize number or connect/create_new_sesssion/login-to-application/disconnect on selenium-remote-server, but maybe it is not the main problem).

**Comment by peroumal1** [comment]
Ok, I get it better. 
Did you try to pass the builder from Test::BDD::Cucumber to T::S::R::D and see if it fixes your issue ? 

```perl 
my $driver = Test::Selenium::Remote::Driver->new(_builder => $the_builder_from_cucumber); 
```

**Comment by tomas-zemres** [comment]
Note that Test::BDD::Cucumber creates new Test::Builder->create for each test-scenario.

 I try to describe the situation in my tests:
(Note that BDD Cucumber has different syntax, but I try to describe how it is executed)
```
# I have global selenium driver:
my $driver = Test::Selenium::Remote::Driver->new();

scenario-1 { # begin of scenario 1  # Test::Builder->create is internally called
  # there is returned different instance from Test::Builder->new()
   
   ok(1 == 1);  # this works fine, because it internally calls Test::Builder->new that returns actual builder.
   ...
   $driver->alert_text_is('abs'); # this failed
}

scenario-2 { # begin of other scenario # Test::Builder->create is internally called
   # there is returned different instance from Test::Builder->new()

  but I am using same $driver instance as in previous test-scenario.
}

**Comment by tomas-zemres** [comment]
Fix is simple, call Test::Builder->new() before each test-call, to get actual builder.
Same as it is implemented in Test::More or other test-modules.

(or is there problem with this solution?)

**Comment by peroumal1** [comment]
The main problem I have with this solution is that I cannot measure the impact of it : sure it would fix your case, but I don't have a clear idea on the implications for other cases and if it would generate other side effects. 
On top of that : 
* as I understand it, you already faced the problem with Test::LongString, now you are facing it with Test::Selenium::Remote::Driver... if you have the same problem with all `Test::` related modules you are using, then there is possibly something wrong with the way you are implementing the tests or with Test::BDD::Cucumber 
* so far we do not have a way of reproducing your error. As far as I can tell, it could be many other things. For instance I just checked the github repo for Test::BDD::Cucumber, and there was this issue related to the [test builder](https://github.com/sheriff/test-bdd-cucumber-perl/issues/47), which could possibly explain what you are experiencing; it also could be a problem with your environment (modules versions, etc), on which we have no information so far. 

So believe me, we are trying to help here, but we need at least some precise information to be able to diagnose the problem and eventually fix it. 

@gempesaw, can you have a look too, we might need a fresh pair of eyes on this one ;)

**Comment by tomas-zemres** [comment]
Yes, it looks like better would be fix Test::BDD::Cucumber::Executor, because other modules may also have one global Test::Builder instance.

**Comment by tomas-zemres** [comment]
I created fix for Test::BDD::Cucumber: https://github.com/sheriff/test-bdd-cucumber-perl/issues/61

**Comment by gempesaw** [comment]
Yes, I've been following along, but my conclusions are pretty similar to yours. without a solid reproducible case, it's tough to justify making changes with unknown side effects, especially since I'm not too familiar with how new instances of Test::Builder interact with each other. I'll keep an eye on the Test::BDD::Cucumber issue as well to see how that goes.

thanks all :)
