### ISSUE TITLE
find_elements does not die

### ISSUE THREAD

**Issue by mauritzhansen** [gempesaw/Selenium-Remote-Driver#214]
Hi folks,

I have looked at the source, and it seems that the intention is that find_elements should behave identical to find_element, in that it should die if the element is not found. However, this does not happen, likely because selenium server does not throw an error.

Is this desired behaviour (of Selenium::Remote::Driver or the selenium server)?

Regards,

Mauritz

**Comment by peroumal1** [comment]
Hello, 

I think it is the 'normal behaviour'. According to the [JSON Wire Protocol spec](https://code.google.com/p/selenium/wiki/JsonWireProtocol#POST_/session/:sessionId/elements), calling `find_elements` does not raise an error if no element is found. So the Selenium Server does not raise an error, and so far our implementation of `find_elements` does not die if no elements are found. 

But our code in that case looks wrongly implemented, but I guess it is a historical copy/paste that we can easily fix.

**Comment by gempesaw** [comment]
Yes, the behavior of `find_elements` is deliberately different from the behavior of `find_element`. 

When `find_element` fails, the selenium server throws an ElementNotFoundException, and we `die` in the perl code with some related message to that exception. But, when the plural version `find_elements` doesn't find elements, the selenium server itself doesn't throw any exceptions - just returns an empty array, so that's what we give the user: `[]`.

`find_elements` will die for other exceptions though; for example, IIRC, if we pass it an invalid xpath, the selenium server throws an InvalidXpathException or something like that, and we manifest that in our perl code as a `die` with the exception text.
