### ISSUE TITLE
replace #!perl shebangs in MockRemoteConnection.pm

### ISSUE THREAD

**Issue by gempesaw** [gempesaw/Selenium-Remote-Driver#221]
> One good thing: the doc's at least didn't use "/usr/bin/perl".

> Catch is that POSIX requirs an absolute path after the #!, which
meanst that examples like:

>     #!perl

> will fail on most systems.

> Instead you can use:

>     #!/bin/env perl

> Ref:

> <http://search.cpan.org/~gempesaw/Selenium-Remote-Driver-0.26/lib/Selenium/Remote/Mock/RemoteConnection.pm>

**Comment by lembark** [comment]
Bunch of #! perl with absolute paths in the ./t contents also. 
These cause problems if someone tries to run them outside of "prove" or "perl -e" since they have a pretty good chance of not referring to the perl executable used to install the module (e.g., perlbrew or mine is /opt/perl). The really screwed up thing is that these have a mix so some of them will get the right executable
others won't. That is less than fun to debug...

Two options: 
(a) Remove the #! lines entirely from *.t files: they are not intended to be run as standalone executables.
(b) At least use "#!/bin/env perl" for all of them, which should get the correct perl on anything *NIX[ish].

I have a copy of the repository and can generate a pull request for whichever you prever [I'd vote for (a)].



 $ grep '^#!' t/*.t
 t/00-load.t:#! /usr/bin/perl
 t/03-spec-coverage.t:#!/bin/env perl
 t/04-commands-implemented.t:#!/usr/bin/perl
 t/CanStartBinary.t:#! /usr/bin/perl
 t/convenience.t:#! /usr/bin/perl
 t/error.t:#! /usr/bin/perl
 t/Finders.t:#! /usr/bin/perl
 t/Firefox-Profile.t:#!/usr/bin/perl
 t/pod.t:#!/bin/env perl -T
 t/Remote-Connection.t:#! /usr/bin/perl
 t/Test-Selenium-Remote-Driver-google.t:#!/usr/bin/env perl
 t/Test-Selenium-Remote-Driver.t:#!/usr/bin/env perl
 t/Test-Selenium-Remote-WebElement.t:#!/bin/env perl
 t/Waiter.t:#! /usr/bin/perl

**Comment by gempesaw** [comment]
I'm happy with (a) - removing them entirely. Any preference, @peroumal1? 

Thanks!

**Comment by peroumal1** [comment]
(a) too. 
BTW, should not it be `#!/usr/bin/env perl` instead of `#!/bin/env perl` ?

**Comment by lembark** [comment]
"env" is used in boot code and normally lives in /bin (holdover from the days when /usr didn't have to be mounted at boot time).

e.g., on my system here:

-rwxr-xr-x 1 root root 31152 Apr  9 12:54 /bin/env
lrwxrwxrwx 1 root root     8 Apr  9 12:54 /usr/bin/env -> /bin/env

**Comment by lembark** [comment]
(1): all of the ./t/*.t files have the #! lines removed. A few of them had "#!perl -T" which did nothing for testing since prove would have bypassed the #! line anyway.

(2) Modify ./lib/Selenium/Remote/Mock/RemoteConnection.pm, update the POD to use "#!/bin/env perl".

(3) Eyeballing the remainder #! lines gets me:
./README.md:#! /usr/bin/perl
./driver-example.pl:#!/usr/bin/perl
./t/bin/record.pl:#! /usr/bin/perl

Note: "/usr/bin/perl" is almost always *not* what you want to be using these days (see <http://www.slideshare.net/lembark/perl-inside-a-box-building-perl-for-docker> for a few of the reasons).

Q: Why the hell does everyone keep naming their executables on *NIX after Perl4 external libraries?
     We don't need "ls.exe" or "find.exe" either: extensions are extraneous to the *NIX shell, they are ignored
      completely. 

README.md is easy (doesn't break any code).
driver-example.pl => replace with #!/bin/env perl
the ./t/bin/record.pl looks like it needs to be executable so I've just changed its #! to /bi/env also.

Leaving:

 $ find . -type f | grep -v '.git' | xargs egrep '#!.*perl'
./README.md:#!/bin/env perl
./driver-example.pl:#!/bin/env perl
./lib/Selenium/Remote/Mock/RemoteConnection.pm:    #!/bin/env perl
./lib/Selenium/Remote/Mock/RemoteConnection.pm:    #!/bin/env perl
./lib/Selenium/Remote/Mock/RemoteConnection.pm:    #!/bin/env perl
./t/bin/record.pl:#!/bin/env perl

making the world safe for PerlBrew once again.

**Comment by lembark** [comment]
There was also a test with a "use 5.10" in it that I removed (it was below the strict & warnings).
Given that perl 5.16 is in "end of life" mode, you might want to think about setting the lowest version supported to something like 5.16 or 5.18.

**Comment by lembark** [comment]
Q: You prefer a patch or should I fork and send back a pull request (can't branch due to lack of commit bit)?

**Comment by gempesaw** [comment]
PRs are easiest for us! :)

thanks for taking a look at all of the instances :)

**Comment by lembark** [comment]
Happy to help.
You should have PR.

**Comment by gempesaw** [comment]
resolved by #224 which was manually merged into master.

thanks all :)
