### ISSUE TITLE
Problem with Switch tabs in Firefox.

### ISSUE THREAD

**Issue by sergiod1981** [gempesaw/Selenium-Remote-Driver#236]
Hi guys.

I can open a new tab with 

```perl
$driver->send_keys_to_active_element(KEYS->{'control'}, 't');
```

but when I try to back to the first tab with.

```perl
$driver->send_keys_to_active_element(KEYS->{'control'}, KEYS->{'page_up'});
```

or

```perl
$driver->send_keys_to_active_element(KEYS->{'control'}, KEYS->{'numpad_1'});
```

nothing happens... I'm confused. How I can switch to first tab? 

thanks a lot

**Comment by gempesaw** [comment]
what happens if you send <kbd>CTRL - T</kbd> again, will it keep working ?

Alternatively, I'm pretty sure that tabs and windows are the same thing to Webdriver. This means you should be able to use [get_window_handles](get_window_handles) and [switch_to_window](https://metacpan.org/pod/Selenium::Remote::Driver#switch_to_window) to switch programatically, instead of trying to keep track of which tab is first/second/third through keyboard actions.

**Comment by sergiod1981** [comment]
thanks for the answer.

I tried as you said.  contrl + t to open a third tab but at this time it is not worked.


then I tried. your suggestion about windows_handles

 my $handles = $driver->get_window_handles;
 $driver->switch_to_window($handles->[0]); # from the second tab to witch to the first tab.  in firefox.-
but nothing happens. didn't work

**Comment by sergiod1981** [comment]
I tested again.
and It is very strange. Repeating the action the switch tab order works.


```perl
$driver->send_keys_to_active_element(KEYS->{'control'}, KEYS->{'numpad_1'});
$driver->send_keys_to_active_element(KEYS->{'control'}, KEYS->{'numpad_1});
```

Can you test it, if you want. to replicate the error. 

my firefox version is 42.0
selenium server 2.48.2
perl version 5.16.3
OS : Windows 7
Module version : 0.27


At the first time. using the orden to switch, the cursor is positioned in the  last character of url address and paste a "1" char it.  at the second time using the same command hte order to switch to the first tab is work.

I don't understand why happend it. 
Maybe is an incompatibility with the new versions of firefox?

thanks for the support guys.

**Comment by gempesaw** [comment]
as a heads up, we've just updated the firefox extension version to the latest 2.48.2, which may (???) help resolve this.

**Comment by gempesaw** [comment]
Oh, actually, I bet the issue here is that you have to de-press the CTRL key after the first time you press it. That is, you should put the `KEYS->{control}` before AND after the `t` so that you're doing a "press ctrl down, press `T`, un-press ctrl". 

For example, this is working on my OS X machine and it creates two tabs:

```perl
use strict;
use warnings;
use Selenium::Remote::Driver;
use Selenium::Remote::WDKeys qw/KEYS/;

my $driver = Selenium::Remote::Driver->new;

$driver->get('https://www.google.com');
$driver->find_element('body', 'tag_name')->click;

my $new_tab_modifier = KEYS->{command_meta}; # substitute "control" if you're windows
$driver->send_keys_to_active_element($new_tab_modifier, 't', $new_tab_modifier);
$driver->send_keys_to_active_element($new_tab_modifier, 't', $new_tab_modifier);

sleep(5);
```

and the version without de-pressing the modifier only creates one tab.
