### ISSUE TITLE
Try::Tiny can't do work

### ISSUE THREAD

**Issue by autodataming** [gempesaw/Selenium-Remote-Driver#242]
```Perl
	my $search_elm=0;
	while(1)
	{
	   if($search_elm==0)
	   {
	       sleep(2);
           try{$search_elm=$driver->find_element_by_xpath('/html/body/div[4]/div[5]/div[1]/div/div[12]/form/div[2]/input')}catch{};
	   }
	   else
	   {
	       last;	
	   }	
		
	}

  $search_elm->click();

```
it still generate  error，

   An element could not be located on the page using the given search parameters: /html/bo
dy/div[4]/div[5]/div[1]/div/div[12]/form/div[2]/input,xpath at D:/perl520/site/lib/Sele
nium/Remote/Finders.pm line 18.
 at D:/perl520/site/lib/Selenium/Remote/Finders.pm line 23.
Can't locate object method "click" via package "0" (perhaps you forgot to load "0"?) at
 scifinder_sele2.pl line 361, <FH> line 1.
  have successfully input the casid

**Comment by gempesaw** [comment]
try{$search_elm=$driver->find_element_by_xpath...

From the [docs](https://metacpan.org/pod/Selenium::Remote::Driver#find_element), `find_element_by_xpath` does _not_ croak when it cannot find an element. So the `try` will never do catch anything, since the sub doesn't throw. 


    Can't locate object method "click" via package "0" (perhaps you forgot to load "0"?) at scifinder_sele2.pl line 361, line 1.

I'm not sure why, but somehow you're getting out of the `while` with $search_elm set to 0, which is the cause of this error message.

FWIW, I use [Selenium::Waiter](https://metacpan.org/pod/Selenium::Waiter) for this pattern of "wait until an element can be found", but there are of course other options, like adjusting [Selenium's built in timeouts](https://metacpan.org/pod/Selenium::Remote::Driver#set_timeout).

    use Selenium::Waiter qw/wait_until/;
    my $d = Selenium::Remote::Driver->new;

    my $div = wait_until { $d->find_element('div', css') };

Coincidentally, using xpath selectors that are so dependent on the DOM structure can lead to flaky tests :(

**Comment by autodataming** [comment]
Thank you very much. You are very  geek and nice.
I think I should  try{$webelement->click}catch{}.
But Selenium::Waiter is a good choice for me. Thank you very much.
