### ISSUE TITLE
 Element is no longer attached to the DOM

### ISSUE THREAD

**Issue by autodataming** [gempesaw/Selenium-Remote-Driver#244]
```Perl
  my $subtext_elm=0;
  
    $subtext_elm=wait_until{$driver->find_element_by_id("substanceIds")};
   
	
    if($debug){print "begin to search casid: $casid\n";}
		
	$subtext_elm->clear();
	$subtext_elm->send_keys($casid);
```

begin to search casid: 331960-72-6
Error while executing command: clearElement: An element command failed because the refe
renced element is no longer attached to the DOM.: Element is no longer attached to the
DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_e
lement_reference.html

what's the reason? sometime it will not happened. sometime it will happen

**Comment by autodataming** [comment]
I try to solve the problem,like this
```Perl
	my $temp=0;
	while(1)
	{	
		$temp=try{$subtext_elm->clear()}catch
		{
		$subtext_elm=wait_until{$driver->find_element_by_id("substanceIds")};		
		0;
		};
		if($temp)
		{
			last;
			
		}
	}
```

**Comment by autodataming** [comment]
can we use code like this
```Perl
wait_until{$subtext_elm->clear()}
```

**Comment by gempesaw** [comment]
> Error while executing command: clearElement: An element command failed because the refe
renced element is no longer attached to the DOM.: Element is no longer attached to the
DOM. For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html

This happens when you use webdriver to find an element. Then, in the web app, the element is deleted/removed/altered in some way. When dealing with an AJAX web app, it's very common that interacting with the page will cause DOM elements to be deleted or moved around. Then, when webdriver tries to interact with the deleted element, it throws an exception when the element is not where webdriver expects it.

To work around this issue, in general, you should try to find the element as close as possible to when you will interact with it. Specifically, you just need to make sure the element in question isn't deleted/removed/moved between the time you find it and by the time you interact with it, and finding it immediately before you interact with it is a good starting point for that.

> can we use code like this

I'd suggest finding the element inside of the wait as well:

```perl
wait_until { 
    my $elem = $driver->find_element('div', 'tag_name');
    $elem->clear;
}
```

But if webdriver isn't clearing the element like you expect, you may need to check the element text or something like that:

```perl
wait_until { 
    my $elem = $driver->find_element('div', 'tag_name');
    $elem->clear;
    return $elem->get_text eq '';
}
```

**Comment by autodataming** [comment]
I will try it. Thank you very much.
