### ISSUE TITLE
need a help to get the toast message contents .

### ISSUE THREAD

**Issue by Rashmi-Nuviso** [gempesaw/Selenium-Remote-Driver#249]
how to get the Toast message contents .
UseCase is as follows.
when a user enters the invalid login password, 
a toast with the "Bad credentials" is thrown .

so how do i catch this message from the selenium and python code .

Any help would be appreciated.

**Comment by gempesaw** [comment]
Hi Rashmi,

It will depend entirely on the toast library you are using. We can't help without at least that much information. The best case scenario would be for you to provide the actual page you're testing, and the entire perl script you're using to run the webdriver test. 

Also note that this is not the python webdriver repo, but instead the perl webdriver repo. If you need help specifically with the python code, you're probably better off asking this question in the [webdriver google group](https://groups.google.com/forum/#!forum/selenium-users).

Regardless of the toast library and the webdriver binding language you're using, the general methodology is the same. The toasts aren't any different from any other elements on the page. You need to find a suitable locator for the toast that appears (this is why the toast library matters, since they all implement their HTML & CSS differently), do a `find_element`, and get the text from the resulting element. There may of course be timing issues - if the toast is not on the screen long enough, you may have trouble verifying that it exists. You may be need to use an implicit timeout, or [`wait_until`](https://metacpan.org/pod/Selenium::Waiter#wait_until) to have your webdriver session sit and loop while looking for the toast text.

Good luck!

**Comment by Rashmi-Nuviso** [comment]
Thanks Daniel for getting back with the comments !!!

As am using the Python web-driver  as per the suggestion will have to use
the wait untill to locate the element with the toast message . Let me check
those

steps .




On Mon, Feb 8, 2016 at 10:06 PM, Daniel Gempesaw <notifications@github.com>
wrote:

> Hi Rashmi,
>
> It will depend entirely on the toast library you are using. We can't help
> without at least that much information. The best case scenario would be for
> you to provide the actual page you're testing, and the entire perl script
> you're using to run the webdriver test.
>
> Also note that this is not the python webdriver repo, but instead the perl
> webdriver repo. If you need help specifically with the python code, you're
> probably better off asking this question in the webdriver google group
> <https://groups.google.com/forum/#!forum/selenium-users>.
>
> Regardless of the toast library and the webdriver binding language you're
> using, the general methodology is the same. The toasts aren't any different
> from any other elements on the page. You need to find a suitable locator
> for the toast that appears (this is why the toast library matters, since
> they all implement their HTML & CSS differently), do a find_element, and
> get the text from the resulting element. There may of course be timing
> issues - if the toast is not on the screen long enough, you may have
> trouble verifying that it exists. You may be need to use an implicit
> timeout, or wait_until
> <https://metacpan.org/pod/Selenium::Waiter#wait_until> to have your
> webdriver session sit and loop while looking for the toast text.
>
> Good luck!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gempesaw/Selenium-Remote-Driver/issues/249#issuecomment-181425015>
> .
>



-- 
Thanks,
Rashmi B S
Nuviso Networks
Ph: 8904190375

**Comment by gempesaw** [comment]
You've also posted relevant comments at the end of #108 as well; looks like this is done. Thanks!
