### ISSUE TITLE
Error handler is called, but no errors occured

### ISSUE THREAD

**Issue by PunchyRascal** [gempesaw/Selenium-Remote-Driver#253]
When I use a custom error handler, and call the method 'find_no_element_ok', error handler is called, even though the test passes ok.

Reproduce using this test: (it should pass after the fix)

[ReproduceSeleniumBug.txt](https://github.com/gempesaw/Selenium-Remote-Driver/files/176047/ReproduceSeleniumBug.txt)

**Comment by gempesaw** [comment]
Looks like this is a valid bug, the interaction took me a while to track down but I'm pretty sure this is how it's going:

1. `find_no_element_ok` eventually resolves to `_check_ok` in `T::S::R::Role::DoesTesting`
2. `check_ok` calls `$self->$method(@r_args)` with `$method === find_element`
3. `find_element` does a literal `Carp::croak` as documented in the [`error_handler` POD](https://metacpan.org/pod/Selenium::Remote::Driver#error_handler) when no element is found
4. That `croak` is caught by the [`around '_execute_command'`](https://github.com/gempesaw/Selenium-Remote-Driver/blob/95282e1a3f9ed38b61964ee885d68cada69dde98/lib/Selenium/Remote/Driver.pm#L574) that decorates `execute_command` to enable the `error_handler` functionality
5. The `around` has a `try/catch` and in the `catch` block we're finally calling `error_handler`, but we shouldn't be, since the intent of `find_no_element_ok` is to be okay with not finding an element 

My first thought is to fix this in `::Role::DoesTesting::_check_ok` with an additional logic branch specifically for the `find_no_element` case that does a `find_elements` and asserts that the response array length is 0. How does that sound @peroumal1 ?
