### ISSUE TITLE
Downloading images with selenium-remote-driver

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#254]
Is this possible?

**Comment by teodesian** [comment]
Actually, it is.  I wrote a function some time ago to exfiltrate an image via execute_async_script() as a base64'd string, and then write it to the provided file.  I call the function get_base64, but if there is sufficient interest in me adding this function to the distribution, we can call it whatever we like.

**Comment by gempesaw** [comment]
What is the test case you're trying to do? 

If you're interested in downloading an image from the page to analyze it during the test, teodesian's solution is probably of interest. 

If your web app is offering an image for download that you'd like to assert is available, and/or you'd like to check that your images are properly referenced (aka no 404s or 403s, "all the images are appearing on the page"), Webdriver may not be necessary. For example, It may be sufficient to make HEAD calls to the image URL from a scripting language of your choice, instead of necessitating a whole webdriver instance.

**Comment by teodesian** [comment]
Made a PR with said function in it for your consideration.
https://github.com/gempesaw/Selenium-Remote-Driver/pull/255
