### ISSUE TITLE
Firefox 45.0.1 won't load webdriver.xpi (2.48.2)

### ISSUE THREAD

**Issue by andyjack** [gempesaw/Selenium-Remote-Driver#260]
Our test machines went from 45.0 to 45.0.1 this morning, and now our S:R:D tests are failing.  I hacked in 2.53.0 webdriver.xpi and they are working again.

Is packaging the .xpi with S:R:D the best way to track such a dependency?

**Comment by gempesaw** [comment]
> Is packaging the .xpi with S:R:D the best way to track such a dependency?

Maybe not! It does have the downside of requiring a new release to keep the `webdriver.xpi` updated. What's an alternative ... it'd have to download the xpi from somewhere (presumably the selenium-release.storage.google-apis.com website), store it locally, and be able to figure out when there's a newer version of Selenium available. It'd also mean some delay during the first run of Selenium::Firefox.

Also, to be clear, you're using Selenium::Firefox and thus running into issues with the `webdriver.xpi` that is packaged in the repo, right? Because I wouldn't expect these FF upgrade compatibility issues if you're S::R::D along with the standalone selenium server jar.

**Comment by andyjack** [comment]
> Also, to be clear, you're using Selenium::Firefox and thus running into issues with the webdriver.xpi that is packaged in the repo, right? Because I wouldn't expect these FF upgrade compatibility issues if you're S::R::D along with the standalone selenium server jar.

Correct, I'm creating the selenium object in an environment without the selenium server running:
```
use Selenium::Firefox;
my $srd = Selenium::Firefox->new;
my $base_uri = 'http://localhost:3000';
$srd->get($base_uri);
```

gives 'Unable to connect to the /usr/bin/firefox binary on port 9090 at /opt/perl5.20.2/lib/site_perl/5.20.2/Selenium/CanStartBinary.pm line 132.'

```
$ aptitude show firefox | grep Version
Version: 45.0.1+build1-0ubuntu0.14.04.2
```

To handle the xpi dependency, maybe have a constructor option to let the user specify the path to the `.xpi` and `prefs.json` files, or to supply the `.jar` file and S:R:D pulls the relevant files out?  Downloading the latest server jar in the background might also be acceptable, depending on the end user's preferences.

**Comment by gempesaw** [comment]
Ah! Passing in a filepath to the `.jar` sounds like a good idea!

**Comment by remorse** [comment]
Hi! Can you explain how you "hacked in 2.53.0 webdriver.xpi"? I just ran into this problem, and I would like to be able to solve it...

Thanks,
Ricky

**Comment by andyjack** [comment]
Hi remorse, quick and dirty hack is:
* unzip the server standalone .jar file from https://selenium-release.storage.googleapis.com/index.html?path=2.53/
* find webdriver.xpi and webdriver_prefs.json from the jar, copy those over existing .xpi and .json files in your installed Selenium::Remote::Driver distribution

Note that as of Firefox 47, selenium webdriver 2.53.0 does not work. More work needs to be done for S:R:D to use the new marionette driver, see #271.

**Comment by remorse** [comment]
Thanks! I will worry about Firefox 47 when that comes around; for now I just need 45 to work, and now it does!

**Comment by gempesaw** [comment]
fwiw, via [comment in seleniumhq/selenium#2110](https://github.com/seleniumhq/selenium/issues/2110#issuecomment-229184275), they've released a corresponding bump version of the standalone jar: 2.53.1. the same steps that andyjack outlined should now work with firefox 47.0.1.

ideally I'd get a release out for this asap, but I can't get the recordings working on windows. :(

**Comment by gempesaw** [comment]
Support for binary startup via geckodriver of FF48 was just released in v1.00 of S::R::D. Unfortunately, v1.00 contains breaking changes for using Selenium::Firefox to drive FF47. That is because v1.00 automatically enables `geckodriver` mode in Selenium::Firefox, but FF47 [doesn't work with `geckodriver`](https://github.com/angular/webdriver-manager/issues/52#issuecomment-229922136). So, to use v1.00 with FF47, you need to disable marionette, as mentioned in [the docs](https://metacpan.org/pod/release/GEMPESAW/Selenium-Remote-Driver-1.00/lib/Selenium/Firefox.pm#BREAKING-CHANGES). Because these are breaking changes from 0.2701 , we bumped a major version of S::R::D in the spirit of semver and all.

Honestly, if you've updated the `.xpi` locally to support FF47 and you're happy running the tests on FF47, there's no need to update for the time being. If you want to run tests on FF48 or require some of the other changes in the v1.00 release, then hopefully the docs are clear on how to start up your desired FF version.

If you upgrade to S::R::D@1.00 and FF48 together, then everything should continue working, as v1.00 assumes FF48 & `geckodriver`, as mentioned, although you will need to download `geckodriver` and put it in `$PATH` or provide it during instantiation.

**Comment by sandeepjain1987** [comment]
I am facing the same problem on FF 49b9 , Sel beta 3 jar and gecko v.10.0. Any fix available ?

**Comment by gempesaw** [comment]
Hi @sandeepjain1987, this issue is already closed. Also, if you're using the sel3.0-beta3 jar, your problem is different from what this issue is about. Can you please create a new issue for your problem? 

Additionally, with only the information you've provided, it's difficult to diagnose your issue. Can you also provide the version of S::R::D your'e using, the perl code you're using to start up FF, and what error message in Perl, if any, you're seeing? Since you're using the selenium beta 3 jar, the selenium server log is also very useful; please provide that as well. Thanks!

**Comment by sandeepjain1987** [comment]
Sorry to post this question at the wrong place. I have created a new issue https://github.com/gempesaw/Selenium-Remote-Driver/issues/277 . Logs are available there.
