### ISSUE TITLE
Trouble finding certain element

### ISSUE THREAD

**Issue by nick2012** [gempesaw/Selenium-Remote-Driver#297]
How come that in firefox dev console this works:

```
$$('a[href*="keywords"]');
Array [ <a#tt_u1>, <a#t_u1._ff> ]
```

But in Perl all these attempts return unitialized:
```

#1)
my $entity = $driver->find_element_by_css('a[href*="keywords"]');

#2)
my $entity = $driver->find_elements('a[href*="keywords"]',"css");

#3)
my $entity = $driver->find_elements('//a/@href[contains(., "keywords")]');


#4)
my $entity = find_element_custom($driver, 'a[href*="keywords"]');

sub find_element_custom
{
my ($driver, $input_string) = @_;
my $script = q{
       var arg1 = arguments[0];
       var callback = arguments[arguments.length-1];
       var elem = window.document.querySelectorAll(arg1);
       callback(elem);
   };
my $elem = $driver->execute_async_script($script,$input_string);
return $elem;
}
```

What am I doing wrong?

**Comment by gempesaw** [comment]
Dunno! Everything looks good from what you've posted, but I'm not sure what debugging I can offer without a repro case: the webpage where this is happening and a perl script to produce the errant behavior. If it's an internal page that's not accessible to outsiders, then you'd have to publish a snippet of the HTML that still reproduces the error with an appropriate perl script for that snippet.

Otherwise, I'm not sure I can be of much assistance; from what you've presented so far, I can't see any issues to explain the behavior you're seeing.
