### ISSUE TITLE
ask if an element exist.

### ISSUE THREAD

**Issue by sergiod1981** [gempesaw/Selenium-Remote-Driver#96]
I need to ask in my script if an element exist or not. and create steps for yes or no.

How I can evaluate if an element exist or not (also I need to skip the step if the element doesn't exist)

thanks a lot.

**Comment by glenwolf** [comment]
Hmm. I was just fiddling with the `send_keys` sub in S::R::D, and it seems that you have to get rather obtuse when an element you want is not findable.

That is, when using `find_elements->[n]->send_keys($some_text)`, if the array returned by `find_elements` is empty, then the `send_keys` call will crash the server, just as if we had been unable to find something using `find_element`.

My specific code looks like
`$twd->find_elements("#some_id")->[0]->send_keys($some_text);`

**Comment by gempesaw** [comment]
Hm, I don't usually invoke `find_element` directly, having wrapped it in a sub that apparently prevents the server from crashing, but I haven't looked at my wrapper in a while, so I'm not sure what it is that keeps my sessions alive. I'll have to double check that. 

For your case @glenwolf, perhaps it's possible that we can do a check within S::R::WebElement to see that $self actually has an `id` ? Just thinking off the top of my head, not actually looking at any code yet...

**Comment by glenwolf** [comment]
The issue there is that the crash is actually caused by the find_elements failing to find anything, so that any further call (as in `get_attribute`, etc) will cause a crash. The most correct solution, as things stand, is to confirm that the array actually has a length (e.g. use it in scalar context in an if-statement) before attempting to `send_keys` to it. But this seems like unnecessary padding.

I definitely feel that in this situation, a warning should be generated and then the command skipped, so that the programmer has the choice to flag a `die` or just let the script skip the intended action. I do this (inefficiently) through a try/catch block, but I'd rather not be forced into that situation.

**Comment by gempesaw** [comment]
Hmm, I'm not sure what we can do from within `find_elements`. Or maybe I still don't understand the issue.

```perl
#! /usr/bin/perl

use strict;
use warnings;
use feature qw/say/;
use Selenium::Remote::Driver;

my $d = Selenium::Remote::Driver->new;
$d->get('http://www.google.com');

say $d->find_elements('missing')->[0]->send_keys('zzz');
```

gives 

```
Can't call method "send_keys" on an undefined value at /Users/dgempesaw/webdriver.pl line 12.
```

The crash I'm seeing is entirely client side, and not the browser or selenium server, when we try to `undef->send_keys`. We can `carp` or something from within `find_elements` if we find out that there are no elements in the return array, but I don't know how to stop a user from dereferencing the array and trying to invoke a method on `undef`. Is there something we can do that I don't know about to prevent/help that?

I guess, actually, brian d foy made like a ... [null object thing](http://stackoverflow.com/a/7068271/1156644) that basically returns itself for any subroutine calls on it, something to the effect of

```perl
package Null {
    my $null = bless {}, __PACKAGE__;
    sub AUTOLOAD { $null }
}
```

would return itself for any subroutines invoked against it, so that we could do `send_keys` and `get_attributes` all day long without causing a crash. But then we'd have to check afterwards whether we have an actual WebElement that we did things to, vs the Null thing.

We could put that kind of thing in under a config option when instantiating, if you want to defer the validation until afterwards and instead of doing your own try/catch or eval/die. Or something...

**Comment by glenwolf** [comment]
Actually, Daniel has a very good point. I hadn't even thought about the
fact that the crash from that undefined method was on the client side. I'm
not sure that it really helps us at all, at least directly, but that does
definitely isolate the problem. And the idea of using the null object class
is an interesting solution.

Hmm, just did some poking around in the source. Looks like the
`find_elements` method is literally built to croak whenever it gets an
error message. Which is an interesting response... But that means that
there is basically no way to prevent the program crashing whenever it hits
an error from failing to find an element. So, that's bollocks...

**Comment by gempesaw** [comment]
> Hmm, just did some poking around in the source. Looks like the `find_elements` method is literally built to croak whenever it gets an error message. 

Yeah, this is true - it does `eval` and then checks `$@`. But, for `find_elements` (plural), finding 0 elements doesn't throw an exception. find_elements can throw an exception on the server for different reasons, like an invalid xpath expression for example: https://gist.github.com/gempesaw/0473b78f43c1a7654d7c

> But that means that there is basically no way to prevent the program crashing whenever it hits an error from failing to find an element. 

singular `find_element`: try/catch, or `find_elements` first and check size
plural `find_elements`: check size of array after it returns

Neither of those are clean, but I think it's pretty standard practice amongst all the webdriver bindings to treat those java Exceptions as something to die on and make the user handle try/catching them, or doing a `find_elements` before a potentially missing `find_element`. For example, the [C# bindings](http://iainrose.tumblr.com/post/28060274976/using-by-objects-to-verify-if-webelement-present) and the ruby watir bindings kill the script when attempting to find a missing element, and require the user to circumvent the issue manually. With watir, we see the same exact issue: we must begin/rescue (aka try/catch) or else find_element kills us.

```
require 'watir-webdriver'

browser = Watir::Browser.new :firefox
browser.goto "http://google.com"
begin
  browser.text_field(:name => 'missing').set("WebDriver rocks!")
rescue
  puts 'We must explicitly catch this failed find_element'
end

puts 'Or else it will kill the script'
browser.text_field(:name => 'missing').set("WebDriver rocks!")
```

I agree that it's a big PITA that the test dies on an unexpectedly un-found element, but I can also see that from the test's point of view, not being able to find an element is a big deal - it does seem like a death-worthy event, unless the programmer has explicitly prepared for it. For all we know, the entire script depends on that element being around and able to do things; better to die sooner close to the issue than later down the road.

I also take responsibility for the fact that this isn't clear. I need to make this information/workarounds publicly available in the readme/pod/wiki instead of forcing everyone to dig into the guts of `find_elements?` with me, no matter how much fun it is :P

**Comment by gempesaw** [comment]
@singerko does [`get_element_location_in_view`](https://metacpan.org/pod/Selenium::Remote::WebElement#get_element_location_in_view) help? Note that although it should try to scroll your element into focus, it's entirely possible that your application has something still blocking it, like a sticker header/footer/popover ad/hidden element/blah/blah/blah. I can't do much about that, but it is definitely a pain point.

**Comment by glenwolf** [comment]
Sigh. Yeah, yeah, standardization is good. And for most testing
functionality it makes sense. But it certainly is a pain for rapid
automation. But hey, I'll just go ahead and take a note from every good
PAUSE user ever and make a module that does what I want, instead of
complaining xD

I'm going to try to throw together a Try::Selenium::Remote::Driver. Same
general concept as T::S::R::D (hmm, just realized that I'm going to
obfuscate that namespace, so I should probably work up a better name), but
wraps everything in a try/catch block, with an optional bool "fatal" that
can be used locally (or with a default setting) to make a call, well,
fatal. Just changing the method calls to things like `try_find_element` and
`try_find_ok`, so that it's not overloading the existing namespace. I'm
also considering adopting some of `WWW::Selenium`'s syntax, such as
providing a `try_click('some_query')` method. As far as I can tell, the
`click` method doesn't return a WebElement object, so it makes sense to me
for it to accept a search-query as an optional argument, so that one can
use it as a standalone command (i.e. `$driver->click('.my_element', 'css')`
). Anyway, that's all just floating around my head right now. Because the
commands are procedurally generated by Moo, it's a bit of a hassle to try
to capture all of the commands in a try/catch block. And it definitely
prevents me from more explicit error message handling for said blocks.

Unless of course, you feel like helping me out? I figure you're in the best
position to make it happen as simply as possible.

**Comment by gempesaw** [comment]
Can we accomplish that with autoload ?

```perl
package StopDyingAllTheTimeGeeeeez;
use Try::Tiny;
use Moo;
extends 'Selenium::Remote::Driver';

sub AUTOLOAD {
    # chop off the try_ from the subroutine name, ie `try_click` -> `click`
    # figure out where in @_ AUTOLOAD puts $self and @args

    return try {
        $self->$actual_method_name(@args)
    } 
    catch {
        say "sorry, haven't the slightest idea what to do with: " . $_;
    }
}
```

or something? I think T::S::R::D used to do sømething like this once upon a time, but it was removed. 

https://github.com/gempesaw/Selenium-Remote-Driver/blob/f77949d/lib/Test/Selenium/Remote/Driver.pm#L38

It may be of interest. I definitely see the utility in your class - when I started with S::R::D I didn't know any better, so I did end up manually wrapping every call to $driver in a try/catch. I've now gotten slightly less ignorant and I'd like to remove them, but I'm also more lazy now, so they've stayed in tact :P

**Comment by glenwolf** [comment]
I've considered autoboxing/autoloading to deal with it. The problem is
that, even chipping off the accessory "try_", we would still be used with a
variety of commands that don't translate 1-to-1 with S::R::D, so the method
would still have to figure out how to chain things. Even if we managed to
collect the correct error message and stack trace for any given call, the
actual handling of different methods would require some hand-coded
definition. Basically, what I'm saying is that the creation of the script
can absolutely be automated (obviously), but that won't be able to complete
the task. And that still means creating a big switch-block (I'm quite fond
of the experimental `given/when` syntax, though I really shouldn't use it
in published modules). So, mostly, I'm trying to be lazy. Oops.

Also, ha, your keyboard wrote a ø (or so it seems on my browser). Are you
Norwegian?

**Comment by gempesaw** [comment]
in summary, the options are now:

1.  `find_element` will croak _the perl app_ if the element is not found. wrap it in a `try/catch` or `eval` block manually to keep the perl script alive.

2.  `find_elements` will return an empty array if the element is not found. the script _must_ check the size of the array after searching to keep the script alive. invoking a method on the result of `find_elements` like `$d->find_elements->[0]->get_text` without checking runs the risk of killing _the perl app_ due to invoking a method on the first element of an empty array.

3. parameterised versions of the find_element sub have been installed as of the latest release: see https://metacpan.org/pod/Selenium::Remote::Driver#find_element_by_class.

```perl
my $d = Selenium::Chrome->new;
my $elem = $d->find_element_by_xpath('//xpath');
print 'we will always make it here, regardless of whether or not the element exists.';

$elem->get_text;
print 'if the element is missing, the above line will kill the perl script';
```

in general, it is the perl code that chooses to croak/die, not the browser session itself. so, although any S:R:D method in perl can croak due to an exception, the browser is always still alive. catching the exception with `try/catch` or `eval` will keep the perl script alive and allow the test to continue executing.
